#ifndef __PATH_H__
#define __PATH_H__


/*
    linux kernel define
    
    enum {LAST_NORM, LAST_ROOT, LAST_DOT, LAST_DOTDOT, LAST_BIND};
*/

enum {

    PATH_NORMAL,
    PATH_ROOT,
    PATH_DOT,
    PATH_DOTDOT,
    PATH_BIND,
};


enum {LAST_NORM, LAST_ROOT, LAST_DOT, LAST_DOTDOT, LAST_BIND};


#define LOOKUP_READLINK		1 << 0
#define LOOKUP_NO_LAST_DIR	1 << 1
#define LOOKUP_LAST_DIR		1 << 2

#define LOOKUP_FOLLOW		0x0001  //我定义LOOUP_FOLLOW 文件必须存在非创建
#define LOOKUP_DIRECTORY	0x0002
#define LOOKUP_AUTOMOUNT	0x0004
#define LOOKUP_CREAT    0x0008


#define LOOKUP_PARENT		0x0010
#define LOOKUP_REVAL		0x0020
#define LOOKUP_RCU		0x0040
#define LOOKUP_NO_REVAL		0x0080


#define LOOKUP_OPEN		0x0100
#define LOOKUP_CREATE		0x0200
#define LOOKUP_EXCL		0x0400
#define LOOKUP_RENAME_TARGET	0x0800

#define LOOKUP_JUMPED		0x1000
#define LOOKUP_ROOT		0x2000
#define LOOKUP_EMPTY		0x4000
#define LOOKUP_DOWN		0x8000



#endif
